/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_mindquarry_desktop_workspace_MacSVNHelper */

#ifndef _Included_com_mindquarry_desktop_workspace_MacSVNHelper
#define _Included_com_mindquarry_desktop_workspace_MacSVNHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mindquarry_desktop_workspace_MacSVNHelper_CONFLICT_RESET_FROM_SERVER
#define com_mindquarry_desktop_workspace_MacSVNHelper_CONFLICT_RESET_FROM_SERVER 0L
#undef com_mindquarry_desktop_workspace_MacSVNHelper_CONFLICT_OVERRIDE_FROM_WC
#define com_mindquarry_desktop_workspace_MacSVNHelper_CONFLICT_OVERRIDE_FROM_WC 1L
/*
 * Class:     com_mindquarry_desktop_workspace_MacSVNHelper
 * Method:    onNotify
 * Signature: (Lorg/tigris/subversion/javahl/NotifyInformation;)V
 */
JNIEXPORT void JNICALL Java_com_mindquarry_desktop_workspace_MacSVNHelper_onNotify
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mindquarry_desktop_workspace_MacSVNHelper
 * Method:    getCommitMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mindquarry_desktop_workspace_MacSVNHelper_getCommitMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
