// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('titleText', { text: unescape('Hello%2C World!') });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('bodyText', { text: 'Quick read-and-write access to your Mindquarry Wiki.' });
    CreateText('text', { text: 'Wiki URL' });
    CreateText('text13', { text: 'Username' });
    CreateText('text16', { text: 'Password' });
}
window.addEventListener('load', setupParts, false);
