#!/bin/sh
BASEDIR=`dirname $0`
JAVADIR="$BASEDIR/../Resources/Java/"
CLASSPATH="."
for jar in $( ls $JAVADIR/*.jar ); do
  CLASSPATH="$CLASSPATH:$jar"
done
echo java -XstartOnFirstThread -classpath $CLASSPATH org.eclipse.swt.MindClientWrapper > /tmp/client.log
java -XstartOnFirstThread -classpath $CLASSPATH org.eclipse.swt.MindClientWrapper >> /tmp/client.log
#echo $CLASSPATH >> /Users/lars/Documents/Teamspaces/mindquarry-desktop-client/mindquarry-desktop-client/date.txt

